---

# Install zsh #
- name: Install ZSH Ubuntu
  apt: name=zsh state=latest
  become: true
  when: ansible_os_family == "Debian"

- name: Install ZSH Mac
  homebrew: name=zsh state=latest
  when: ansible_os_family == "Darwin"

# Install oh-my-zsh
- name: Install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh
    update: yes
    accept_hostkey: yes

# .zshrc #
- stat:
    path: ~/.zshrc
  register: zsh_config

- name: Backup .zshrc
  copy:
    src: ~/.zshrc
    dest: ~/.zshrc_backup
  when: zsh_config.stat.islnk is defined and zsh_config.stat.islnk == False

- name: Link .zshrc
  file: src={{ role_path }}/conf/.zshrc dest=~/.zshrc state=link force=true
  when: remote is not defined

- name: Copy .zshrc
  copy: src={{ role_path }}/conf/.zshrc dest=~/.zshrc backup=true force=true
  when: remote is defined and remote

# template #
- name: Clone zsh template
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel9k
    update: no
    accept_hostkey: yes

- name: Download PowerLine fonts
  git:
    repo: https://github.com/powerline/fonts.git
    dest: ~/.oh-my-zsh/custom/fonts/powerline
    update: no
    accept_hostkey: yes

- name: Install PowerLine fonts
  shell: cd ~/.oh-my-zsh/custom/fonts/powerline && ./install.sh

# zsh as default shell #
- name: Set ZSH as users shell.
  become: yes
  user:
    name: "{{ user }}"
    shell: /usr/bin/zsh