---
- include: ubuntu.yml
  name: Ubuntu apps
  become: true
  when: ansible_distribution == 'Debian'

- include: freebsd.yml
  name: FreeBSD apps
  become: true
  when: ansible_distribution == 'FreeBSD'

- include: mac.yml
  name: Mac apps
  when: ansible_distribution == 'Darwin'